### PR TITLE
get ready for grunt v1.0.0

### PR DESCRIPTION
**Pull request by steveoh**
Fixes https://github.com/gruntjs/grunt-docs/blob/master/Blog-2016-02-11-Grunt-1.0.0-rc1-released.md#peer-dependencies

### CODE REVIEW

**Comment by steveoh** [comment]
Hey @israelroldan, @chuckmo or @andrewrjones can you accept this? No one can use this plugin if they upgraded grunt to > 1.

**Comment by israelroldan** [comment]
@steveoh Thanks for your contribution!

**Comment by Jako** [comment]
Maybe you should release a new version with that change. The old package.json is cached somewhere (not locally) for some reason.

**Comment by ravipuranapanda** [comment]
Please release a new version with that change to accept grunt > 0.4. The old package.json is cached somewhere (not locally) for some reason.

**Pull request merged**
